# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='conversion_rate',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='model',
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
    ]
