# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20161127_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('note1', models.CharField(blank=True, max_length=100)),
                ('note2', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='add_inventory',
            old_name='amount',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product_type'),
        ),
    ]
